# .github/workflows/merge-upstream.yml
# merges the upstream repository into this one weekly

name: Merge Upstream Branches
on:
  schedule:
    - cron: "*/5 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Merge upstream
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote add upstream https://github.com/fexofenadine/brcm63xx-tch.git
        git fetch upstream
        git remote -v
        git checkout master
        MERGE_RESULT=$(git merge --no-edit upstream/master)
        if [[ $MERGE_RESULT != *"Already up to date."* ]]; then
          git commit -m "Merged upstream"  
          git push origin master
        fi
        
